packages:
  - apps/*
  - packages/*

allowBuilds:
  '@firebase/util': false
  '@sentry/cli': true
  esbuild: true
  msw: true
  protobufjs: false
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
