ALTER TABLE "inventory"."inventory_events" DROP CONSTRAINT "inventory_events_event_type_check";--> statement-breakpoint
ALTER TABLE "inventory"."inventory_events" DROP CONSTRAINT "inventory_events_quantity_check";--> statement-breakpoint
ALTER TABLE "inventory"."inventory_events" DROP CONSTRAINT "inventory_events_non_stock_cost_blank_check";--> statement-breakpoint ALTER TABLE "inventory"."inventory_events" DROP CONSTRAINT IF EXISTS "inventory_events_purchase_receipt_correction_check";--> statement-breakpoint
ALTER TABLE "inventory"."inventory_events" ADD CONSTRAINT "inventory_events_purchase_receipt_correction_check" CHECK (event_type <> 'purchase_receipt_correction' OR (reference_type = 'purchase_order' AND lot_id IS NULL));--> statement-breakpoint ALTER TABLE "inventory"."inventory_events" DROP CONSTRAINT IF EXISTS "inventory_events_event_type_check";--> statement-breakpoint
ALTER TABLE "inventory"."inventory_events" ADD CONSTRAINT "inventory_events_event_type_check" CHECK (event_type IN ('opening_balance', 'purchase_receipt', 'manufacturing_output', 'manual_adjustment_increase', 'stocktake_gain', 'manufacturing_variance_gain', 'manual_adjustment_decrease', 'stocktake_loss', 'sales_consumption', 'manufacturing_ingredient_consumption', 'manufacturing_variance_loss', 'quality_scrap', 'unpick_restock', 'transfer_out', 'transfer_in', 'quality_disposition_change', 'demand_increase', 'demand_release', 'expected_increase', 'expected_release', 'cost_basis_change', 'landed_cost_revaluation', 'purchase_receipt_correction', 'stocktake_verification'));--> statement-breakpoint ALTER TABLE "inventory"."inventory_events" DROP CONSTRAINT IF EXISTS "inventory_events_quantity_check";--> statement-breakpoint
ALTER TABLE "inventory"."inventory_events" ADD CONSTRAINT "inventory_events_quantity_check" CHECK (CASE
          WHEN event_type IN ('stocktake_verification', 'cost_basis_change', 'landed_cost_revaluation', 'purchase_receipt_correction') THEN quantity = 0
          ELSE quantity > 0
        END);--> statement-breakpoint ALTER TABLE "inventory"."inventory_events" DROP CONSTRAINT IF EXISTS "inventory_events_non_stock_cost_blank_check";--> statement-breakpoint
ALTER TABLE "inventory"."inventory_events" ADD CONSTRAINT "inventory_events_non_stock_cost_blank_check" CHECK (event_type NOT IN ('demand_increase', 'demand_release', 'expected_increase', 'expected_release', 'cost_basis_change', 'purchase_receipt_correction', 'stocktake_verification') OR (lot_id IS NULL AND unit_cost IS NULL AND extended_cost IS NULL));
