import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { Client } from "pg";

export const DEFAULT_ADMIN_URL =
  "postgresql://postgres:postgres@127.0.0.1:5432/postgres";
export const DEFAULT_APP_USER = "app_user";
export const DEFAULT_APP_PASSWORD = "postgres";
export const WORKTREE_ENV_HEADER =
  "# Worktree-local DB overrides. Generated by `pnpm db:local:setup`.\n";
const COMPOSE_FILENAMES = ["compose.yaml", "compose.yml"] as const;

function sleep(ms: number) {
  return new Promise((resolvePromise) => setTimeout(resolvePromise, ms));
}

export function quoteIdentifier(value: string) {
  return `"${value.replaceAll('"', '""')}"`;
}

export function quoteLiteral(value: string) {
  return `'${value.replaceAll("'", "''")}'`;
}

export function getGitTopLevel(cwd = process.cwd()) {
  return execFileSync("git", ["rev-parse", "--show-toplevel"], {
    cwd,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "inherit"],
  }).trim();
}

export function getCommonRepoRoot(cwd = process.cwd()) {
  const commonDir = execFileSync("git", ["rev-parse", "--git-common-dir"], {
    cwd,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  }).trim();

  return dirname(resolve(cwd, commonDir));
}

export function resolveComposeDir(...candidates: string[]) {
  const checked = new Set<string>();

  for (const candidate of candidates) {
    if (!candidate) {
      continue;
    }

    const resolvedCandidate = resolve(candidate);
    if (checked.has(resolvedCandidate)) {
      continue;
    }

    checked.add(resolvedCandidate);

    if (
      COMPOSE_FILENAMES.some((fileName) =>
        existsSync(join(resolvedCandidate, fileName))
      )
    ) {
      return resolvedCandidate;
    }
  }

  throw new Error(
    `Could not find compose.yaml for local Postgres. Checked: ${Array.from(checked).join(", ")}`
  );
}

export function sanitizeSlug(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

export function deriveDatabaseName(worktreeRoot: string) {
  const worktreeName = sanitizeSlug(basename(worktreeRoot)) || "local";
  const hash = createHash("sha1").update(worktreeRoot).digest("hex").slice(0, 8);
  const prefix = "erp_";
  const suffix = `_${hash}`;
  const maxSlugLength = 63 - prefix.length - suffix.length;
  return `${prefix}${worktreeName.slice(0, maxSlugLength)}${suffix}`;
}

export async function canConnect(connectionString: string) {
  const client = new Client({ connectionString });

  try {
    await client.connect();
    return true;
  } catch {
    return false;
  } finally {
    await client.end().catch(() => undefined);
  }
}

export async function waitForPostgres(connectionString: string, timeoutMs = 30_000) {
  const startedAt = Date.now();

  while (Date.now() - startedAt < timeoutMs) {
    if (await canConnect(connectionString)) {
      return;
    }

    await sleep(1_000);
  }

  throw new Error(`Timed out waiting for Postgres at ${connectionString}.`);
}

export function runDockerCompose(
  args: string[],
  cwd: string,
  stdio: "inherit" | "pipe" = "inherit"
) {
  return execFileSync("docker", ["compose", ...args], {
    cwd,
    encoding: "utf8",
    stdio: stdio === "inherit" ? "inherit" : ["ignore", "pipe", "pipe"],
  });
}

export async function ensureLocalPostgresAvailable(
  adminUrl: string,
  composeDir: string
) {
  if (await canConnect(adminUrl)) {
    return { startedDocker: false };
  }

  if (process.env.LOCAL_DB_ADMIN_URL) {
    throw new Error(
      `Could not connect to LOCAL_DB_ADMIN_URL (${adminUrl}). Start that Postgres instance first.`
    );
  }

  console.log("Local Postgres is not running. Starting the shared Docker container...");
  runDockerCompose(["up", "-d", "postgres"], composeDir);
  await waitForPostgres(adminUrl);
  return { startedDocker: true };
}

export function isDockerPostgresRunning(composeDir: string) {
  try {
    const output = runDockerCompose(
      ["ps", "--services", "--status", "running", "postgres"],
      composeDir,
      "pipe"
    );
    return output
      .split("\n")
      .map((line) => line.trim())
      .includes("postgres");
  } catch {
    return false;
  }
}
